//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___DisplayLogic: class {
}

class ___VARIABLE_sceneName___ViewController: UINavigationController, ___VARIABLE_sceneName___DisplayLogic {
  var interactor: ___VARIABLE_sceneName___BusinessLogic?
  var router: (NSObjectProtocol & ___VARIABLE_sceneName___RoutingLogic & ___VARIABLE_sceneName___DataPassing)?

  // MARK: Object lifecycle

  init(configurator: ___VARIABLE_sceneName___Configurator = ___VARIABLE_sceneName___Configurator()) {
    super.init(nibName: nil, bundle: nil)
    configurator.configure(viewController: self)
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    ___VARIABLE_sceneName___Configurator().configure(viewController: self)
  }

  // MARK: Setup

  // MARK: Routing

  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }

  // MARK: View lifecycle

  override func viewDidLoad() {
    super.viewDidLoad()
  }

  //@IBOutlet weak var nameTextField: UITextField!
}
